Moving media presenter out of app
liviaw/magic-composition pull request #21
Opened 2021-02-04 05:33 UTC by liviaw

create instance of media presenter inside index.tsx and pass into App.css

2021-02-04 05:36 UTC, juliamitchelmore commented
Please request review from https://github.com/SamuelDrinkwater 👍

2021-02-05 05:39 UTC, SamuelDrinkwater requested changes
Mostly looks good. Fix up the presenter import/export and then 👍

2021-02-05 05:39 UTC, SamuelDrinkwater commented on src/Components/MediaPresenter.ts
> +const mediaPresenter = new MediaPresenter();
This isn't exported or used in this file. You could either remove this line or export it and import the instance in `App.tsx`

2021-02-05 06:20 UTC, SamuelDrinkwater approved these changes
Nice work 🎉

2021-02-05 06:22 UTC, merged